### ISSUE TITLE
Implement UnixDomainSocketLircClient

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/JavaLircClient#1]
[Useful links](http://stackoverflow.com/questions/170600/unix-socket-implementation-for-java)

Cf. https://github.com/bengtmartensson/harctoolboxbundle/issues/155

**Comment by leamas** [comment]
Well, continuing from previous issue, my point is that  installing a socat wrapper  could be part of regular lirc. Actually, I have been thinking about deprecating --listen, replacing it with something similar to lircd-uinput in an effort to simplify the central scheduler which is part of lircd. So, we  could have something like  _systemd enable lircd-javasocket_ or so. Which perhaps is less problems than installing JNI-based stuff, which always is a bit clumsy. 

EDIT: OTOH, if direct access to the the socket is feasible, it's of course easier and fits the overall bill for some lircd java bindings.

**Comment by bengtmartensson** [comment]
> I have been thinking about deprecating --listen, replacing it with something similar to lircd-uinput in an effort to simplify the central scheduler which is part of lircd. So, we could have something like systemd enable lircd-javasocket or so.

To me, this sounds like a complicated and error prone solution to a problem we do not have...

PS. pythonic LircClient may be on its way...
